### ISSUE TITLE
iOS9 - UICollectionViewFlowLayout has cached frame mismatch for index path

### ISSUE THREAD

**Issue by fwaddle** [keighl/KTCenterFlowLayout#13]
Hi,

After a recent upgrade to iOS9, I started seeing this warning on the console:

UICollectionViewFlowLayout has cached frame mismatch for index path <NSIndexPath: 0xc000000000000016> {length = 2, path = 0 - 0} - cached value: {{9.75, 0}, {55, 65}}; expected value: {{0, 0}, {55, 65}}
This is likely occurring because the flow layout subclass KTCenterFlowLayout is modifying attributes returned by UICollectionViewFlowLayout without copying them

Changing :
`NSMutableArray *superAttributes = [NSMutableArray arrayWithArray:[super layoutAttributesForElementsInRect:rect]];`

to

`NSMutableArray *superAttributes = [NSMutableArray arrayWithArray:[super layoutAttributesForElementsInRect:rect].copy];`

Fixed the issue.

Hope that helps.

**Comment by keighl** [comment]
Thank you kindly!

**Comment by TripleJB** [comment]
From time to time my collection view was not displaying any cells and throw the mentioned error. I recently updated to version 1.1.1 because of this issue.  But still sometimes the collection view displays no cells. Only a white screen. However I am able scroll and interact with outer UI elements, that are not part of the collection view.
