### ISSUE TITLE
Class should override `layoutAttributesForItemAtIndexPath:`

### ISSUE THREAD

**Issue by markst** [keighl/KTCenterFlowLayout#2]

**Comment by keighl** [comment]
@markst is that necessary since this extends `UICollectionViewFlowLayout`, and not vanilla `UICollectionViewLayout`? In flow-layout, I thought `layoutAttributesForItemAtIndexPath` gets the attributes from `layoutAttributesForElementsInRect` anyway. 

Are you getting an unexpected layout because of it?
